name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS

    - name: Set environment variables for Docker
      run: |
        echo "${{ secrets.MY_ENV_FILE }}" > .env

    - name: Set up GCP Service Account key
      run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}" > storage/keys/gcp-service-account.json

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag josetor101/apollosgearshop:latest
      
    - name: Docker Push
      run: docker push josetor101/apollosgearshop:latest
