name: OWASP ZAP Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  owasp-zap:
    runs-on: ubuntu-latest

    services:
      zap:
        image: zaproxy/zap-stable
        options: --health-cmd "zap-cli --health-check" --health-timeout 30s --health-retries 3
        ports:
          - 8080:8080

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, bcmath, zip, gd, mysqli
        coverage: xdebug

    - name: Install Composer dependencies
      run: |
        composer install --no-interaction --prefer-dist

    - name: Set up environment variables
      run: |
        cp .env.example .env
        php artisan key:generate
        php artisan migrate --env=testing

    - name: Start Laravel app in the background
      run: |
        nohup php artisan serve --host=0.0.0.0 --port=8000 &
        sleep 15

    - name: Start OWASP ZAP and perform security scan
      run: |
        docker run --rm -t zaproxy/zap-stable zap-full-scan.py \
          -t http://localhost:8000
          -g gen.conf -r zap_report.html
        
    - name: Upload OWASP ZAP report to GitHub Actions
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: zap_report.html

    - name: Print OWASP ZAP scan results
      run: cat zap_report.html
